site_name: Μια σύγχρονη προσέγγιση στη γλώσσα C
theme:
  name: material
  language: en
  features:
    #-navigation.tabs
    #-navigation.prune
    -content.code.copy
    -toc.follow
    #-toc.integrate

extra_css:
  - 'css/styles.css'

markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - footnotes
  - markdown_grid_tables
  - pymdownx.mark
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      base_path: ["docs"]
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
  
plugins:
    - search
    - awesome-pages

copyright: | 
  Τζάλλας Αλέξανδρος, Γκόγκος Χρήστος, Τσούλος Ιωάννης &copy 2025

